### ISSUE TITLE
Pengen dapet ini

### ISSUE THREAD

**Issue by frmdeveloper** [sadteams/bot-md#11]
![](https://raw.githubusercontent.com/Schweinepriester/github-profile-achievements/main/images/quickdraw-default.png)

**Comment by Kangsad01** [comment]
> ![](https://raw.githubusercontent.com/Schweinepriester/github-profile-achievements/main/images/quickdraw-default.png)

🗿

**Comment by frmdeveloper** [comment]
2 menit lagi

**Comment by frmdeveloper** [comment]
1 menit lagi

**Comment by Kangsad01** [comment]
Awokawok udh dapet

**Comment by frmdeveloper** [comment]
![Screenshot_20220716-140729](https://user-images.githubusercontent.com/80396521/179344328-c6962194-cfd7-4da3-b170-5e69f16e0ef0.png)

**Comment by Kangsad01** [comment]
Awokawokawok 🗿

**Comment by frmdeveloper** [comment]
Terus apa manfaat nya

**Comment by Kangsad01** [comment]
> Terus apa manfaat nya

Pajangan awokawok
