### ISSUE TITLE
Virus alert while downloaded the repo

### ISSUE THREAD

**Issue by zatu22** [sadteams/bot-md#16]
We blocked this dangerous page for your protection:
https://codeload.github.com/sadteams/bot-md/zip/refs/heads/master
Threat name: JS.Heur.Calisto.2.1.A8F7B6B4.Gen
Dangerous pages attempt to install software that can harm the device, gather personal information or operate without your consent.

**Comment by Kangsad01** [comment]
> Kami memblokir laman berbahaya ini demi perlindungan Anda: https://codeload.github.com/sadteams/bot-md/zip/refs/heads/master Nama ancaman: JS.Heur.Calisto.2.1.A8F7B6B4.Gen Laman berbahaya berusaha untuk menginstal perangkat lunak yang dapat membahayakan perangkat, mengumpulkan informasi pribadi, atau beroperasi tanpa persetujuan Anda.

how to fix it?
