### ISSUE TITLE
Install module

### ISSUE THREAD

**Issue by ilhamn2405** [sadteams/bot-md#22]
![Uploading Screenshot_20220914-191236.jpg…]()
Di termux ko npm Install ko gabisa ya, ada solusi ngga bang?

**Comment by ilhamn2405** [comment]
![Screenshot_20220914-191236](https://user-images.githubusercontent.com/43334234/190152527-b3cd3824-1a27-4621-a1df-e80d781a7fc6.jpg)

**Comment by Kangsad01** [comment]
> ![Screenshot_20220914-191236](https://user-images.githubusercontent.com/43334234/190152527-b3cd3824-1a27-4621-a1df-e80d781a7fc6.jpg)

Sc gak sup termux, coba yarn aja
